import type { Metadata } from "next";
import "./globals.css";
import { Barriecito } from "next/font/google";

const barriecito = Barriecito({
  variable: "--font-barriecito",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barriecito.variable}`}>{children}</body>
    </html>
  );
}
